import { from } from 'rxjs';

export * from './dashboard-header/dashboard-header.component';
export * from './transaction-view/transaction-view.component';
export * from './transfer-recipient/transfer-recipient.component';
export * from './otpcard/otpcard.component';
export * from './bank-details/bank-details.component';
export * from './withdraw-bank-details/withdraw-bank-details.component';
export * from './buygold-details-view/buygold-details-view.component';
export * from './buygold-top-view/buygold-top-view.component';
export * from './sellgold-details-view/sellgold-details-view.component';
export * from './sellgold-top-view/sellgold-top-view.component';
export * from './shopping-products/shopping-products.component';
export * from './qr-view/qr-view.component';
export * from './buynear-top-view/buynear-top-view.component';
export * from './otpbank/otpbank.component';
export * from './cimbbank-details/cimbbank-details.component';
export * from './cimbbank-transaction/cimbbank-transaction.component';
export * from './matsidenav/matsidenav.component';
export * from './terms-condition/terms-condition.component';
export * from './split-header/split-header.component';