import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Services } from './service';
import { TRANSACTION_TYPE } from 'src/utils';

@Injectable({
  providedIn: 'root'
})
export class Botv2Service {
  public form: any = {};
  public httpHeaders: HttpHeaders;
  public workerId: string;
  public loggedIn: boolean = false;
  public fromBank: string;
  public fromAccount: string;

  // TODO: This should come from cbs
  private BANKLOAD_FEE = 0.3;
  private BOT_URL = "http://localhost:8000";
  
  constructor(private services: Services, private httpClient: HttpClient) {}

  doInitialize() {
    return this.httpClient.post(this.BOT_URL + "/drivers/initialize", 
      { driver: "selenium" }, { headers: { "Content-Type": "application/json" } }
    ).toPromise();

  }

  doHealthCheck() {
    return this.httpClient.post(this.BOT_URL + "/drivers/health", 
      {}, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();
  }

  doLoginStep1(){
    const data = {
      "flow": this.fromBank,
      "action": "login_step1",
      "with": {
        "username": this.form.username
      }
    }

    return this.httpClient.post(this.BOT_URL + "/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();

  }

  doLoginStep2(){
    const data = {
      "flow": this.fromBank,
      "action": "login_step2",
      "with": {
        "password": this.form.password
      }
    }

    return this.httpClient.post(this.BOT_URL + "/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();    
  }

  doGotoXferPage() {
    const data = {
      "flow": this.fromBank,
      "action": "goto_xfer_page",
      "with": {}
    }

    return this.httpClient.post(this.BOT_URL + "/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();     
  }

  async doFillXferForm() {
    // TODO: This will later be replaced by order number generated by CBS
    const TFR_ORDERNUM = {
      "accountId": this.services.userAccount.id, 
      "amount": this.form.amount, 
      "description": "D8P", 
      "transactionTypeId": TRANSACTION_TYPE.BankLoad  
    };

    const data = {
      "flow": this.fromBank,
      "action": "fill_xfer_form",
      "with": {
        "fromaccount": this.fromAccount,
        "amount": (this.form.amount + this.BANKLOAD_FEE).toString(),
        "txndet": JSON.stringify(TFR_ORDERNUM)
      }
    }

    return this.httpClient.post(this.BOT_URL + "/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();    
  }

  doConfirmTxn(opts) {
    var payload = {}
    if ('tacRequired' in opts && opts["tacRequired"] == true) {
      payload["tac"] = this.form.tac.toString()
    }
    const data = {
      "flow": this.fromBank,
      "action": "confirm_txn",
      "with": payload
    }

    return this.  httpClient.post(this.BOT_URL + "/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();    
  }
  
  doGetTxnStatus() {
    const data = {
      "flow": this.fromBank,
      "action": "get_txn_status",
      "with": {}
    }

    return this.httpClient.post(this.BOT_URL + "/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();  
  }

  doLogout() {
    const data = {
      "flow": this.fromBank,
      "action": "logout",
      "with": {}
    }

    console.log("Logging out...");

    if (this.loggedIn) {
      return this.httpClient.post(this.BOT_URL + "/flows/execute", 
        data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
      ).toPromise()
      .catch((err) => {
        console.log(err);        
      })
      .finally(() => {
        // Finally quit the driver
        this.doQuit();
      })
    }
    else {
      // Finally quit the driver
      this.doQuit();
    }
  }

  doQuit() {
    console.log("Quitting...");
    
    return this.httpClient.post(this.BOT_URL + "/drivers/quit", 
      {}, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise()
    .then(() => {
      console.log(`Releasing worker id ${sessionStorage.getItem("worker_id")}...`);        
      sessionStorage.removeItem("worker_id");
    })
    .catch((err) => {
      console.log(err);        
    });
  }

  doWithdraw(params:any) {
    const bankData = params.bank
    const TFR_ORDERNUM = "\""+{
      "accountId": "\""+this.services.userAccount.id+"\"", 
      "amount": "\""+params.amount+"\"", 
      "description": "\""+params.desc+"\"", 
      "transactionTypeId": "\""+TRANSACTION_TYPE.Withdraw+"\"" 
    }+"\"";

    const data = {
      "bank": bankData.bankName,
      "toaccount": bankData.bankAccNumber,
      "amount":params.amount,
      "ordernum": TFR_ORDERNUM,
      "beneficiary": bankData.bankAccName
    }
    return this.httpClient.post(this.BOT_URL + "/withdrawals",data, { headers: { "Content-Type": "application/json"} }
    ).toPromise();
  }
}