import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Services } from './service';
import { TRANSACTION_TYPE } from 'src/utils';

@Injectable({
  providedIn: 'root'
})
export class Botv2Service {
  public form: any = {};
  public httpHeaders: HttpHeaders;
  public workerId: string;
  public loggedIn: boolean = false;
  public fromBank: string;
  public fromAccount: string;

  constructor(private services: Services, private httpClient: HttpClient) {}

  doInitialize() {
    return this.httpClient.post("http://localhost:8000/drivers/initialize", 
      { driver: "selenium" }, { headers: { "Content-Type": "application/json" } }
    ).toPromise();

  }

  doHealthCheck() {
    return this.httpClient.post("http://localhost:8000/drivers/health", 
      {}, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();
  }

  doLoginStep1(){
    const data = {
      "flow": this.fromBank,
      "action": "login_step1",
      "with": {
        "username": this.form.username
      }
    }

    return this.httpClient.post("http://localhost:8000/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();

  }

  doLoginStep2(){
    const data = {
      "flow": this.fromBank,
      "action": "login_step2",
      "with": {
        "password": this.form.password
      }
    }

    return this.httpClient.post("http://localhost:8000/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();    
  }

  doGotoXferPage() {
    const data = {
      "flow": this.fromBank,
      "action": "goto_xfer_page",
      "with": {}
    }

    return this.httpClient.post("http://localhost:8000/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();     
  }

  async doFillXferForm() {
    // TODO: This will later be replaced by order number generated by CBS
    const TFR_ORDERNUM = {
      "accountId": this.services.userAccount.id, 
      "amount": this.form.amount, 
      "description": "D8P", 
      "transactionTypeId": TRANSACTION_TYPE.BankLoad  
    };

    const data = {
      "flow": this.fromBank,
      "action": "fill_xfer_form",
      "with": {
        "fromaccount": this.fromAccount,
        "amount": this.form.amount.toString(),
        "txndet": JSON.stringify(TFR_ORDERNUM)
      }
    }

    return this.httpClient.post("http://localhost:8000/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();    
  }

  doConfirmTxn() {
    const data = {
      "flow": this.fromBank,
      "action": "confirm_txn",
      "with": {
        "tac": this.form.tac.toString()
      }
    }

    return this.  httpClient.post("http://localhost:8000/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();    
  }
  
  doGetTxnStatus() {
    const data = {
      "flow": this.fromBank,
      "action": "get_txn_status",
      "with": {}
    }

    return this.httpClient.post("http://localhost:8000/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).toPromise();  
  }

  doLogout() {
    const data = {
      "flow": this.fromBank,
      "action": "logout",
      "with": {}
    }

    console.log("Logging out...");

    if (this.loggedIn) 
      return this.httpClient.post("http://localhost:8000/flows/execute", 
        data, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
      ).toPromise()
      .catch((err) => {
        console.log(err);        
      })
      .finally(() => {
        // Finally quit the driver
        this.doQuit();
      })
  }

  doQuit() {
    console.log("Quitting...");
    
    this.httpClient.post("http://localhost:8000/drivers/quit", 
      {}, { headers: { "Content-Type": "application/json", "Worker-Id": this.workerId } }
    ).subscribe();
  }
}