import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Services } from './service';
import { TRANSACTION_TYPE } from 'src/utils';

@Injectable({
  providedIn: 'root'
})
export class Botv2Service {
  public form: any = {};
  public httpHeaders: HttpHeaders;
  public workerId: string;
  public loggedIn: boolean = false;
  public bankLoad: any = {};

  private BOT_AUTH = "Basic Ym90X2F3OTM4MzE6MTIzNDU2";  

  constructor(private services: Services, private httpClient: HttpClient) {}

  doInitialize() {
    return this.httpClient.post("/drivers/initialize", 
      { driver: "selenium" }, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH } }
    ).toPromise();
  }

  doHealthCheck() {
    return this.httpClient.post("/drivers/health", 
      {}, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise();
  }

  doLoginStep1(){
    const data = {
      "flow": this.bankLoad.fromBank,
      "action": "login_step1",
      "with": {
        "username": this.form.username
      }
    }

    return this.httpClient.post("/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise();
  }

  doLoginStep2(){
    const data = {
      "flow": this.bankLoad.fromBank,
      "action": "login_step2",
      "with": {
        "password": this.form.password
      }
    }

    return this.httpClient.post("/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise();    
  }

  doLoginStep3(){
    const data = {
      "flow": this.bankLoad.fromBank,
      "action": "login_step3",
      "with": {
        "captcha": this.form.captchaText
      }
    }

    return this.httpClient.post("/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise();    
  }

  doGotoXferPage() {
    const data = {
      "flow": this.bankLoad.fromBank,
      "action": "goto_xfer_page",
      "with": {}
    }

    return this.httpClient.post("/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise();     
  }

  async doFillXferForm() {
    // TODO: This will later be replaced by order number generated by CBS
    const TFR_ORDERNUM = {
      "accountId": this.services.userAccount.id, 
      "amount": this.form.amount, 
      "description": "D8P", 
      "transactionTypeId": TRANSACTION_TYPE.BankLoad  
    };

    const data = {
      "flow": this.bankLoad.fromBank,
      "action": "fill_xfer_form",
      "with": {
        "fromaccount": this.bankLoad.fromAccount,
        "amount": (this.form.amount + this.bankLoad.transactionFee).toString(),
        "txndet": JSON.stringify(TFR_ORDERNUM)
      }
    }

    return this.httpClient.post("/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise();    
  }

  doConfirmTxn(opts) {
    var payload = {}
    if ("tacRequired" in opts && opts["tacRequired"] == true) {
      payload["tac"] = this.form.tac.toString()
    }
    const data = {
      "flow": this.bankLoad.fromBank,
      "action": "confirm_txn",
      "with": payload
    }

    return this.  httpClient.post("/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise();    
  }
  
  doGetTxnStatus() {
    const data = {
      "flow": this.bankLoad.fromBank,
      "action": "get_txn_status",
      "with": {}
    }

    return this.httpClient.post("/flows/execute", 
      data, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise();  
  }

  doLogout() {
    const data = {
      "flow": this.bankLoad.fromBank,
      "action": "logout",
      "with": {}
    }

    console.log("Logging out...");

    if (this.loggedIn) {
      return this.httpClient.post("/flows/execute", 
        data, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
      ).toPromise()
      .catch((err) => {
        console.log(err);        
      })
      .finally(() => {
        // Finally quit the driver
        this.doQuit();
      })
    }
    else {
      // Finally quit the driver
      this.doQuit();
    }
  }

  doQuit() {
    if (this.workerId == undefined)
      return
    
    console.log("Quitting...");
    
    return this.httpClient.post("/drivers/quit", 
      {}, { headers: { "Content-Type": "application/json", "Authorization": this.BOT_AUTH, "Worker-Id": this.workerId } }
    ).toPromise()
    .then(() => {
      console.log(`Releasing worker id ${sessionStorage.getItem("worker_id")}...`);        
      sessionStorage.removeItem("worker_id");
    })
    .catch((err) => {
      console.log(err);
      
      if (err.error == "Worker not claimed!")
        sessionStorage.removeItem("worker_id");
    });
  }

  doWithdraw(params:any) {
    const bankData = params.bank
    
    const TFR_ORDERNUM = {
      "accountId": this.services.userAccount.id, 
      "amount": params.amount, 
      "description": params.desc, 
      "transactionTypeId": TRANSACTION_TYPE.Withdraw  
    };

    // const data = {
    //   "bank": bankData.bankName,
    //   "toaccount": bankData.bankAccNumber,
    //   "amount": params.amount,
    //   "ordernum": TFR_ORDERNUM,
    //   "beneficiary": bankData.bankAccName
    // }

    const data = {
      "bank": bankData.id.toString(),
      "beneficiary": bankData.bankAccName,
      "beneid": params.nationalId,
      "email": params.email,
      "toccount": bankData.bankAccNumber,
      "amount": params.amount.toString(),
      "ordernum": JSON.stringify(TFR_ORDERNUM)
      }

    return this.httpClient.post("/withdrawals",data, { headers: { "Content-Type": "application/json"} }
    ).toPromise();
  }
}